version: '3.8'

services:
  ai-mermaid:
    build: .
    image: tw199501/ai-mermaid:1.0.4
    container_name: ai-mermaid
    ports:
      - "3000:3000"
    env_file:  # 使用 env_file 來載入 .env 文件
      - .env  
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

