services:
  ai-dataset:
    image: ghcr.io/conardli/ai-dataset
    container_name: ai-dataset
    ports:
      - '1717:1717'
    volumes:
    - ./local-db:/app/local-db
    - ./prisma:/app/prisma
    restart: unless-stopped
