version: '3.8'
services:
  ai-mermaid:
    build: .
    image: ai-mermaid:1.0.6
    container_name: ai-mermaid
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
