version: '3.8'
services:
  ai-mermaid:
    build: .
    image: tw199501/ai-mermaid:1.0.8
    container_name: ai-mermaid
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
